# Generated by Django 3.2.8 on 2021-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORWAapp', '0002_salesorder_allocated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='problem_parts',
            field=models.BooleanField(default=False, verbose_name='Problem parts checked'),
        ),
    ]
