# Generated by Django 3.2.8 on 2021-12-02 13:02

import ORWAapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORWAapp', '0003_alter_parts_problem_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='completed_paperwork',
            field=models.FileField(blank=True, upload_to=ORWAapp.models.update_filename_complete),
        ),
    ]
