# Generated by Django 3.2.8 on 2021-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORWAapp', '0004_salesorder_completed_paperwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='notes',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
