# Generated by Django 3.2.8 on 2021-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORWAapp', '0005_alter_parts_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IssueEmails',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='ORWAReminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
