# Generated by Django 3.2.8 on 2021-12-22 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORWAapp', '0006_auto_20211208_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='SMT',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='parts',
            name='notes',
            field=models.TextField(blank=True, max_length=256, verbose_name='Part notes'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ORWA_lines',
            field=models.IntegerField(default=1, help_text='number of lines that are an ORWA', validators=[django.core.validators.MinValueValidator(1, message='less that 1 line at ORWA')]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(help_text='1S###### or SAMP####', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='Order number is too short')]),
        ),
    ]
